version: "3.8"
services:
  qphim:
    build: .
    container_name: qphim
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
